FROM node:16-alpine

ENV NODE_ENV=development

RUN apk update \
  && apk upgrade \
  && apk add --no-cache \
  make python3 git
 
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . /app

CMD ["npm", "start"]

EXPOSE 80