FROM node:16-alpine

ENV NODE_ENV=development

RUN apk update \
  && apk upgrade \
  && apk add --no-cache \
  make python3 git
 
WORKDIR /app
COPY . /app

RUN npm install --legacy-peer-deps

CMD ["npm", "start"]

EXPOSE 80