version: 2.1

executors:
    js:
        docker:
            - image: circleci/node:12.13.1
        working_directory: ~/expo-project
        environment:
            YARN_CACHE_FOLDER: ~/yarn_cache

    android:
        resource_class: xlarge
        docker:
            - image: dsokal/expo-turtle-android
        working_directory: ~/expo-project
        environment:
            EXPO_SDK_VERSION: ${APP_EXPO_SDK_VERSION}
            TURTLE_VERSION: ${TURTLE_VERSION_NEW}
            PLATFORM: android
            YARN_CACHE_FOLDER: ~/yarn_cache

commands:
    add_yarn_binaries_to_path:
        steps:
            - run:
                  name: Add yarn binaries path to $PATH
                  command: echo 'export PATH=~/.yarn/bin:$PATH' >> $BASH_ENV

    determine_turtle_cache_key_component:
        steps:
            - run:
                  name: Determine Turtle cache key component
                  command: echo $TURTLE_VERSION $PLATFORM > /tmp/turtle-version-platform

    restore_turtle_cache:
        steps:
            - restore_cache:
                  keys:
                      - cache-turtle-cli-{{ checksum "/tmp/turtle-version-platform" }}

    save_turtle_cache:
        steps:
            - save_cache:
                  paths:
                      - ~/.turtle
                      - ~/yarn_cache
                  key: cache-turtle-cli-{{ checksum "/tmp/turtle-version-platform" }}

    setup_turtle:
        steps:
            - run:
                  name: Setting up environment for Turtle
                  command: turtle setup:$PLATFORM --sdk-version $EXPO_SDK_VERSION

    restore_yarn_cache:
        parameters:
            platform:
                type: string
        steps:
            - restore_cache:
                  keys:
                      - cache-yarn-<< parameters.platform >>-{{ checksum "package.json" }}

    save_yarn_cache:
        parameters:
            platform:
                type: string
        steps:
            - save_cache:
                  paths:
                      - ~/yarn_cache
                  key: cache-yarn-<< parameters.platform >>-{{ checksum "package.json" }}

workflows:
    version: 2
    builds:
        jobs:
            - publish_app
            - build_android_apk:
                  requires:
                      - publish_app
            - set_completed:
                  requires:
                      - build_android_apk

jobs:
    publish_app:
        executor: js
        steps:
            - checkout
            - add_yarn_binaries_to_path
            - restore_yarn_cache:
                  platform: linux
            - run:
                  name: Installing expo-cli
                  command: yarn global add expo-cli
            - run:
                  name: Installing cmd packages
                  command: 'cd ~/expo-project/commands && yarn'
            - run:
                  name: Set bulding
                  command: 'cd ~/expo-project/commands && node ./updateStatus.js BUILDING'
            - run:
                  name: Publishing Expo app
                  command: |
                      expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
                      yarn
                      expo publish
            - save_yarn_cache:
                  platform: linux

    set_completed:
        executor: js
        steps:
          - run:
              name: Upload apk
              command: 'cd ~/expo-project/commands && node ./uploadFile.js android ~/expo-project.apk'
          - run:
            name: Set completed build
            command: 'cd ~/expo-project/commands && node ./updateStatus.js COMPLETED'

    build_android_apk:
        executor: android
        steps:
            - checkout
            - restore_yarn_cache:
                  platform: linux
            - run: yarn
            - save_yarn_cache:
                  platform: linux
            - add_yarn_binaries_to_path
            - determine_turtle_cache_key_component
            - restore_turtle_cache
            - run:
                  name: Installing gulp-cli & turtle-cli
                  command: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
            - setup_turtle
            - save_turtle_cache
            - run:
                  name: Preparing env script
                  command: 'cd ~/expo-project/commands && node ./prepareAndroidEnv.js'
            - run:
                  name: Set mobile config environment
                  command: source setEnv.sh && cat ~/expo-project/setEnv.sh
            - run:
                  name: Building Expo standalone app
                  command: |
                      echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
                      base64 --decode expo-project.jks.base64 > expo-project.jks
                      turtle build:android \
                          --keystore-path ./expo-project.jks \
                          --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS \
                          --type apk \
                          -o ~/expo-project.apk
            - store_artifacts:
                  path: ~/expo-project.apk