version: 2.1

executors:
  js:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/expo-project
    environment:
      YARN_CACHE_FOLDER: ~/yarn_cache

  android:
    resource_class: xlarge
    docker:
      - image: dsokal/expo-turtle-android
    working_directory: ~/expo-project
    environment:
      EXPO_SDK_VERSION: 37.0.0
      TURTLE_VERSION: 0.16.2
      PLATFORM: android
      YARN_CACHE_FOLDER: ~/yarn_cache

  ios:
    macos:
      xcode: 11.1.0
    working_directory: ~/expo-project
    environment:
      EXPO_SDK_VERSION: 37.0.0
      TURTLE_VERSION: 0.16.2
      PLATFORM: ios
      YARN_CACHE_FOLDER: /Users/distiller/yarn_cache
      HOMEBREW_NO_AUTO_UPDATE: 1

commands:
  install_macos_deps:
    steps:
      - run:
          name: Installing jq & node@12
          command: |
            brew install jq node@12
            brew link --overwrite --force node@12

  add_yarn_binaries_to_path:
    steps:
      - run:
          name: Add yarn binaries path to $PATH
          command: echo 'export PATH=~/.yarn/bin:$PATH' >> $BASH_ENV

  set_mobile_config_env:
    steps:
      - run:
          name: Set mobile config environment
          command: |
            chmod +x setEnv.sh
            ./setEnv.sh

  determine_turtle_cache_key_component:
    steps:
      - run:
          name: Determine Turtle cache key component
          command: echo $TURTLE_VERSION $PLATFORM > /tmp/turtle-version-platform

  restore_turtle_cache:
    steps:
      - restore_cache:
          keys:
          - cache-turtle-cli-{{ checksum "/tmp/turtle-version-platform" }}

  save_turtle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.turtle
            - ~/yarn_cache
          key: cache-turtle-cli-{{ checksum "/tmp/turtle-version-platform" }}

  install_turtle_ios:
    steps:
      - run:
          name: Installing turtle-cli
          command: |
            yarn config set prefix ~/.yarn
            yarn global add turtle-cli@$TURTLE_VERSION

  setup_turtle:
    steps:
      - run:
          name: Setting up environment for Turtle
          command: turtle setup:$PLATFORM --sdk-version $EXPO_SDK_VERSION

  restore_yarn_cache:
    parameters:
      platform:
        type: string
    steps:
      - restore_cache:
          keys:
          - cache-yarn-<< parameters.platform >>-{{ checksum "package.json" }}

  save_yarn_cache:
    parameters:
      platform:
        type: string
    steps:
      - save_cache:
          paths:
            - ~/yarn_cache
          key: cache-yarn-<< parameters.platform >>-{{ checksum "package.json" }}

workflows:
  version: 2
  builds:
    jobs:
      - publish_app
      - build_ios_archive:
          requires:
            - publish_app
      - build_android_apk:
          requires:
            - publish_app
      - set_completed:
          requires:
            - build_ios_archive
            - build_android_apk

jobs:
  publish_app:
    executor: js
    steps:
      - checkout
      - add_yarn_binaries_to_path
      - restore_yarn_cache:
          platform: linux
      - run:
          name: Installing expo-cli
          command: yarn global add expo-cli
      - run:
          name: Publishing Expo app
          command: |
            expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
            yarn
            expo publish
      - save_yarn_cache:
          platform: linux

  set_completed:
    executor: js
    steps:
      - run:
          name: Set completed build
          command: curl --data "param1=completed" https://webhook.site/cdec8429-eae3-4ca5-93f1-ba2690de2a16

  build_ios_archive:
    executor: ios
    steps:
      - checkout
      - restore_yarn_cache:
          platform: darwin
      - run: yarn
      - save_yarn_cache:
          platform: darwin
      - install_macos_deps
      - add_yarn_binaries_to_path
      - determine_turtle_cache_key_component
      - restore_turtle_cache
      - install_turtle_ios
      - setup_turtle
      - save_turtle_cache
      - set_mobile_config_env
      - run:
          name: Building Expo standalone app
          command: ./script/ios-build.sh
      - store_artifacts:
          path: ~/expo-project.ipa
      - run:
          name: Upload ipa
          command: curl -F "file=@~/expo-project.ipa" https://webhook.site/cdec8429-eae3-4ca5-93f1-ba2690de2a16

  build_android_apk:
    executor: android
    steps:
      - checkout
      - restore_yarn_cache:
          platform: linux
      - run: yarn
      - save_yarn_cache:
          platform: linux
      - add_yarn_binaries_to_path
      - determine_turtle_cache_key_component
      - restore_turtle_cache
      - run:
          name: Installing gulp-cli & turtle-cli
          command: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - setup_turtle
      - save_turtle_cache
      - set_mobile_config_env
      - run:
          name: Building Expo standalone app
          command: ./script/android-build.sh
      - store_artifacts:
          path: ~/expo-project.apk
      - run:
          name: Upload apk
          command: curl -F "file=@~/expo-project.apk" https://webhook.site/cdec8429-eae3-4ca5-93f1-ba2690de2a16